runtime: python
service: api
env: flex

beta_settings:
  cloud_sql_instances: "cloud-test-1232:europe-west1:db-instance"

automatic_scaling:
  min_instances: 5
  max_instances: 15

handlers:
  - url: /.*
    script: auto
