runtime: python37
service: api

beta_settings:
  cloud_sql_instances: "cloud-test-1232:europe-west1:db-instance"

automatic_scaling:
  min_instances: 5
  max_instances: 15
  target_cpu_utilization: 0.7
  target_throughput_utilization: 100
  max_concurrent_requests: 50

handlers:
  - url: /.*
    script: auto
