#Functions

import random

def GenerateRandomNumbers():
    random_numbers = []
    for i in range(1000):
        random_numbers.append(random.randint(0, 100000))

    return random_numbers

#End Points

from flask import Flask

app = Flask(__name__)

random_numbers_storage = 'random-numbers-storage'

@app.route('/')
def root():
    return 'This is the Api'

@app.route('/GenerateNumbers')
def GenerateNumbers():
    random_numbers = [random.randint(0,100000) for i in range(1000)]
    
    return 'Random Numbers Have Been Generated: '+random_numbers

@app.route('/GetResults')
def GetResults():
    return "Results"
    #return "Smallest Number Generated by System: "+str(smallest)+" Largest Number Generated by System: "+str(largest)

if __name__ == '__main__':
    app.run()
